# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ml-api'
    metrics_path: '/metrics'
    static_configs:
      # Use network mode "host" or the actual IP address of your host machine
      - targets: ['172.17.0.1:8000']  # This is commonly the docker host IP
        labels:
          service: 'ml-service'
